// Exercícios. Cada um tem: bloco, enunciado, dica, resposta (consulta de referência)
// e "ordem" (true = a ordem das linhas conta na correção).
// A correção compara o resultado da sua consulta com o da resposta; os nomes das colunas não contam.
const EXERCICIOS = [
  // 1. Consultar
  { bloco: "1. Consultar",
    enunciado: "Mostre todas as colunas e todas as linhas da tabela <code>estados</code>.",
    dica: "<code>SELECT *</code> traz todas as colunas. Depois vem <code>FROM</code> e o nome da tabela.",
    resposta: "SELECT * FROM estados;" },
  { bloco: "1. Consultar",
    enunciado: "Mostre o <b>nome</b> e a <b>uf</b> dos estados da região <b>Sul</b>.",
    dica: "Escolha as colunas depois do <code>SELECT</code>, separadas por vírgula. Filtre com <code>WHERE regiao = 'Sul'</code> (texto vai entre aspas simples).",
    resposta: "SELECT nome, uf FROM estados WHERE regiao = 'Sul';" },
  { bloco: "1. Consultar",
    enunciado: "Mostre o <b>nome</b> e a <b>area_km2</b> dos <b>5 maiores</b> estados em área, do maior para o menor.",
    dica: "<code>ORDER BY area_km2 DESC</code> ordena do maior para o menor; <code>LIMIT 5</code> fica só com as 5 primeiras linhas.",
    resposta: "SELECT nome, area_km2 FROM estados ORDER BY area_km2 DESC LIMIT 5;",
    ordem: true },
  { bloco: "1. Consultar",
    enunciado: "Mostre o <b>nome</b> dos municípios de Santa Catarina (<code>codigo_uf = 42</code>) com <b>DDD 48</b>, em ordem alfabética.",
    dica: "Junte duas condições com <code>AND</code>. Ordem alfabética: <code>ORDER BY nome</code>.",
    resposta: "SELECT nome FROM municipios WHERE codigo_uf = 42 AND ddd = 48 ORDER BY nome;",
    ordem: true },
  { bloco: "1. Consultar",
    enunciado: "Mostre o <b>nome</b> dos municípios cujo nome <b>começa com \"Porto\"</b>.",
    dica: "<code>LIKE</code> compara com um padrão; o <code>%</code> vale \"qualquer coisa\". Ex.: <code>nome LIKE 'Porto%'</code>.",
    resposta: "SELECT nome FROM municipios WHERE nome LIKE 'Porto%';" },

  // 2. Resumir
  { bloco: "2. Resumir",
    enunciado: "Quantos municípios existem no Brasil segundo esta base?",
    dica: "<code>COUNT(*)</code> conta as linhas.",
    resposta: "SELECT COUNT(*) FROM municipios;" },
  { bloco: "2. Resumir",
    enunciado: "Para cada <b>codigo_uf</b>, mostre quantos municípios o estado tem. Ordene do maior para o menor total.",
    dica: "<code>GROUP BY codigo_uf</code> junta as linhas de cada estado; <code>COUNT(*)</code> conta dentro de cada grupo. Dê um apelido à contagem (<code>AS total</code>) para usar no <code>ORDER BY</code>.",
    resposta: "SELECT codigo_uf, COUNT(*) AS total FROM municipios GROUP BY codigo_uf ORDER BY total DESC;",
    ordem: true },
  { bloco: "2. Resumir",
    enunciado: "Para cada <b>região</b>, mostre a <b>área média</b> dos estados, arredondada sem casas decimais.",
    dica: "<code>AVG(coluna)</code> calcula a média; <code>ROUND(valor)</code> arredonda.",
    resposta: "SELECT regiao, ROUND(AVG(area_km2)) FROM estados GROUP BY regiao;" },
  { bloco: "2. Resumir",
    enunciado: "Quais <b>codigo_uf</b> têm <b>mais de 400</b> municípios? Mostre o código e o total.",
    dica: "<code>WHERE</code> filtra linhas <i>antes</i> de agrupar; para filtrar <i>depois</i> do <code>GROUP BY</code> use <code>HAVING COUNT(*) &gt; 400</code>.",
    resposta: "SELECT codigo_uf, COUNT(*) FROM municipios GROUP BY codigo_uf HAVING COUNT(*) > 400;" },
  { bloco: "2. Resumir",
    enunciado: "Quantos <b>DDDs diferentes</b> existem em Santa Catarina (<code>codigo_uf = 42</code>)?",
    dica: "<code>COUNT(DISTINCT ddd)</code> conta só os valores diferentes.",
    resposta: "SELECT COUNT(DISTINCT ddd) FROM municipios WHERE codigo_uf = 42;" },

  // 3. Cruzar tabelas
  { bloco: "3. Cruzar tabelas",
    enunciado: "Liste as <b>capitais</b>: a <b>uf</b> (da tabela estados) e o <b>nome</b> do município, em ordem de uf.",
    dica: "<code>JOIN</code> liga as tabelas pela coluna em comum: <code>FROM municipios m JOIN estados e ON e.codigo_uf = m.codigo_uf</code>. Capitais têm <code>capital = 1</code>.",
    resposta: "SELECT e.uf, m.nome FROM municipios m JOIN estados e ON e.codigo_uf = m.codigo_uf WHERE m.capital = 1 ORDER BY e.uf;",
    ordem: true },
  { bloco: "3. Cruzar tabelas",
    enunciado: "Quantos municípios há em cada <b>região</b>?",
    dica: "A região está em <code>estados</code>; os municípios, em <code>municipios</code>. Faça o <code>JOIN</code> e depois <code>GROUP BY e.regiao</code>.",
    resposta: "SELECT e.regiao, COUNT(*) FROM municipios m JOIN estados e ON e.codigo_uf = m.codigo_uf GROUP BY e.regiao;" },
  { bloco: "3. Cruzar tabelas",
    enunciado: "Em quais 5 estados o município tem, em média, a <b>maior área</b>? Mostre a uf e a área do estado dividida pelo número de municípios, com 1 casa decimal, da maior para a menor.",
    dica: "Agrupe por estado e calcule <code>ROUND(e.area_km2 * 1.0 / COUNT(*), 1)</code>. O <code>* 1.0</code> evita a divisão inteira (em SQLite, 7 / 2 = 3).",
    resposta: "SELECT e.uf, ROUND(e.area_km2 * 1.0 / COUNT(*), 1) AS media FROM municipios m JOIN estados e ON e.codigo_uf = m.codigo_uf GROUP BY e.uf ORDER BY media DESC LIMIT 5;",
    ordem: true },

  // 4. Engenharia e recursos avançados
  { bloco: "4. Avançado",
    enunciado: "Quais são os <b>5 municípios mais ao sul</b> do Brasil? Mostre o nome, a uf e a latitude, do mais ao sul para o menos.",
    dica: "Mais ao sul = latitude mais negativa. <code>ORDER BY latitude</code> (crescente) põe os menores primeiro.",
    resposta: "SELECT m.nome, e.uf, m.latitude FROM municipios m JOIN estados e ON e.codigo_uf = m.codigo_uf ORDER BY m.latitude LIMIT 5;",
    ordem: true },
  { bloco: "4. Avançado",
    enunciado: "Qual a <b>distância em linha reta</b> (km) de Florianópolis até cada uma das outras capitais? Mostre as <b>5 mais próximas</b>: nome e distância arredondada sem casas, da menor para a maior.",
    dica: "Use a fórmula de haversine com raio da Terra de 6371 km. Com Florianópolis em <code>f</code> e a outra capital em <code>c</code>:<br><code>6371 * 2 * ASIN(SQRT(POWER(SIN(RADIANS(c.latitude - f.latitude) / 2), 2) + COS(RADIANS(f.latitude)) * COS(RADIANS(c.latitude)) * POWER(SIN(RADIANS(c.longitude - f.longitude) / 2), 2)))</code><br>Para ter Florianópolis numa linha e as capitais noutra, junte a tabela com ela mesma: <code>FROM municipios f JOIN municipios c ON c.capital = 1 AND c.codigo_ibge &lt;&gt; f.codigo_ibge WHERE f.nome = 'Florianópolis'</code>.",
    resposta: "SELECT c.nome, ROUND(6371 * 2 * ASIN(SQRT(POWER(SIN(RADIANS(c.latitude - f.latitude) / 2), 2) + COS(RADIANS(f.latitude)) * COS(RADIANS(c.latitude)) * POWER(SIN(RADIANS(c.longitude - f.longitude) / 2), 2)))) AS km FROM municipios f JOIN municipios c ON c.capital = 1 AND c.codigo_ibge <> f.codigo_ibge WHERE f.nome = 'Florianópolis' ORDER BY km LIMIT 5;",
    ordem: true },
  { bloco: "4. Avançado",
    enunciado: "Para cada estado, qual é o <b>município mais ao norte</b>? Mostre a uf e o nome, em ordem de uf.",
    dica: "Funções de janela numeram linhas dentro de cada grupo sem juntar as linhas: <code>ROW_NUMBER() OVER (PARTITION BY m.codigo_uf ORDER BY m.latitude DESC)</code>. Calcule isso numa subconsulta e fique só com a posição 1.",
    resposta: "SELECT uf, nome FROM (SELECT e.uf, m.nome, ROW_NUMBER() OVER (PARTITION BY m.codigo_uf ORDER BY m.latitude DESC) AS pos FROM municipios m JOIN estados e ON e.codigo_uf = m.codigo_uf) WHERE pos = 1 ORDER BY uf;",
    ordem: true },
];
