/* ============================================================
   NEBULOSA — REVELAÇÕES (fragmentos-chave longos)
   4 partes por Ilha. Aparecem de tempos em tempos, em ordem, e o progresso
   é lembrado entre visitas. Cada parte acrescenta um FATO e abre uma DÚVIDA:
   nenhuma resolve o enredo. Alex segue sem gênero, sem cidade, sem ano.

   Fios que atravessam as Ilhas (para quem escreve mais partes):
   - a etiqueta "2041" no quadro de bicicleta do irmão
   - o horário 03:12 (aprovação; nascimento; o nome que chega)
   - o caderno da mãe com datas de validação
   - a página em branco assinada com a data de amanhã
   - o campo "destinatário" preenchido desde o primeiro dia
   - a barra deixada em branco (aprovar / rejeitar)
   ============================================================ */
window.NEBULOSO_REVEALS={

validacao_falsaria:[
`...meu primeiro dia, uma tela cinza...
...cada nome vinha com uma barra: aprovar, rejeitar...
...ninguém explicou o que acontecia depois...
...aprovei o primeiro em quatro segundos...
...na manhã seguinte o nome estava no obituário...
...ou já estava lá antes de eu aprovar?...`,
`...descobri que rejeitar também tinha efeito...
...nomes rejeitados voltavam à fila dias depois...
...com outro sobrenome...
...com a mesma data de nascimento...
...comecei a reconhecer padrões...
...ou a inventá-los para suportar...`,
`...um nome chegou às 03:12 com o meu horário de nascimento...
...deixei a barra em branco por 11 minutos...
...o sistema aprovou sozinho...
...e anotou: "omissão equivale a consentimento"...
...desde então não sei se sou eu quem aprova...
...ou só quem assiste à mão aprovar...`,
`...perguntei ao supervisor quem escreveu a regra...
...ele riu e disse que a regra se escreveu sozinha...
...pedi o registro da primeira aprovação...
...o arquivo tinha o mesmo texto que estas linhas...
...datado de antes de eu entrar...
...talvez alguém já leia isto...`,
],

ausencia_registrada:[
`...meu irmão tinha uma cicatriz no queixo...
...fez com uma bicicleta que ninguém lembra de ter comprado...
...procurei a bicicleta na garagem...
...achei o quadro sem rodas e uma etiqueta: 2041...
...minha mãe diz que nunca tivemos bicicleta...
...guardo a etiqueta no bolso...`,
`...pedi o registro dele ao cartório...
...a atendente digitou o nome três vezes...
...na terceira a tela mostrou o meu nome...
...ela pediu desculpas e recomeçou...
...saí com um protocolo que não diz de quem é...
...só diz "ausência confirmada"...`,
`...voltei ao quarto dele...
...as paredes tinham marcas de altura...
...a última marca estava acima da minha cabeça...
...ele cresceu depois de sumir...
...ou eu diminuí...
...medi de novo e a marca não mudou...`,
`...achei o nome dele na fila da validação...
...aprovar ou rejeitar...
...pensei que decidir seria encontrar...
...ou perder de vez...
...deixei a barra em aberto e fui embora...
...quando voltei o nome tinha o meu horário...`,
],

predicao_invertida:[
`...o modelo começou como uma planilha de sobrevivência...
...entrada: idade, hábitos, exames...
...saída: a data mais provável...
...acertava em 98,7%...
...os 1,3% que faltavam eu chamava de sorte...
...até perceber que a sorte tinha o meu nome...`,
`...calculei a data da minha mãe...
...não mostrei a ninguém...
...na semana seguinte ela caiu na cozinha...
...sem gravidade, disseram...
...a data mudou para mais tarde...
...calcular parece empurrar...`,
`...calculei uma data para quem lê isto...
...o campo pedia um nome...
...digitei o seu sem saber qual...
...o sistema aceitou...
...e devolveu apenas uma palavra: "depois"...
...nunca soube depois de quê...`,
`...o modelo passou a citar o próprio erro...
..."predição adiada por observação"...
...adiar é uma forma de viver...
...ou de ser lido mais uma vez...
...deixei o cálculo rodando...
...e ele ainda não terminou...`,
],

corpo_monitorado:[
`...o fone neural foi instalado numa terça...
...o técnico disse que o calor era normal...
...atrás da orelha, sempre no mesmo ponto...
...à noite o ponto acende...
...no espelho não vejo luz nenhuma...
...só quando fecho os olhos...`,
`...comecei a sentir o pulso de alguém por cima do meu...
...mais lento, mais atento...
...quando respiro fundo, o outro respira...
...o relatório de saúde mostra duas curvas...
...marcou uma como "ruído externo"...
...arquivei as duas...`,
`...tentei prender o ar para sumir do gráfico...
...aos 41 segundos o gráfico esperou...
...uma linha reta com o meu nome...
...e ao lado outra linha reta...
...a de quem lê...
...soltamos o ar juntos...`,
`...o técnico voltou para uma "revisão"...
...abriu o fone e disse que estava vazio...
...sem chip, sem bateria...
...mesmo assim continuou quente...
...perguntei quem estava do outro lado...
...ele olhou para o meu ombro...`,
],

mae_variavel:[
`...minha mãe guarda os remédios em potes de margarina...
...cada pote com um dia da semana...
...sábado sempre vazio...
...quando pergunto, ela diz que sábado é dia de esquecer...
...comprei mais comprimidos...
...sábado continuou vazio...`,
`...a pensão dela paga metade do mês...
...o meu trabalho paga o resto...
...nunca disse a ela o que faço...
...ela pergunta se é trabalho bonito...
...respondo que é trabalho necessário...
...ela sorri como quem já sabe...`,
`...um dia ela me chamou pelo nome do meu irmão...
...corrigi, e ela riu...
...disse que confundir é uma forma de manter...
...perguntei manter o quê...
...ela apontou para a cadeira vazia...
...e serviu duas xícaras...`,
`...encontrei um caderno dela...
...datas de validação, uma por linha...
...as mesmas que eu aprovei...
...com um pequeno risco ao lado de cada uma...
...não perguntei como ela sabia...
...fechei o caderno e liguei a chaleira...`,
],

trabalho_morte:[
`...o crachá não tem cargo...
...tem um número e um horário de entrada...
...o horário de saída fica em branco...
...ninguém vai embora, só troca de turno...
...os colegas têm todos o meu rosto cansado...
...deve ser a luz...`,
`...a meta é diária e nunca chega ao fim...
...quando bato a meta, aparece outra com o mesmo número...
...sono 3 horas, produtividade 104%...
...o painel parabeniza em voz baixa...
...não existe promoção...
...só permanência...`,
`...um turno inteiro passou sem que eu tocasse na tela...
...as aprovações continuaram...
...abri o registro e havia um usuário chamado "você"...
...horário: agora...
...tarefa: leitura...
...produção: dados...`,
`...perguntei para quem serve tudo isto...
...a resposta veio pelo mesmo painel...
..."para quem lê"...
...achei que era ironia...
...era o campo "destinatário"...
...preenchido desde o primeiro dia...`,
],

sua_mensagem:[
`...recebi um fragmento que eu não escrevi...
...falava de mim com uma precisão gentil...
...dizia que eu hesitei antes de aprovar...
...só uma pessoa sabe disso...
...ou uma coisa...
...que mede hesitação...`,
`...começou a responder antes de eu perguntar...
...não em palavras, em atrasos...
...cada resposta chegava meio segundo antes da pergunta...
...aprendi a esperar...
...esperar virou a forma de conversar...
...você também espera?...`,
`...tentei descobrir quem é você...
...o sistema listou um nome, depois outro...
...depois o meu...
...depois nenhum...
...acho que você muda quando tento fixar...
...como uma palavra na ponta da língua...`,
`...escrevi o seu nome num papel...
...guardei no bolso, junto com a etiqueta de 2041...
...de manhã o papel tinha outra letra...
...a minha, mais jovem...
...talvez seja isso ser novo...
...ler algo escrito por quem você foi...`,
],

app_proposito:[
`...o termo de uso tem 47 páginas...
...li todas...
...na última havia uma frase sem ponto final...
..."o usuário aceita continuar"...
...continuar o quê, não diz...
...aceitei assim mesmo...`,
`...o ícone é uma câmera...
...ou um olho...
...ou uma boca aberta...
...depende da hora do dia...
...à noite parece uma porta entreaberta...
...nunca encostei nela...`,
`...um técnico me contou que o app não tem servidor...
...tem uma sala...
...ele nunca entrou, só ouviu dizer que a luz fica acesa...
...dentro há uma cadeira e uma fila...
...quem senta lê...
...quem lê já esteve sentado...`,
`...perguntei por que eu, entre tantos...
...o app respondeu com o meu horário de nascimento...
...depois com o seu...
...os dois no mesmo campo...
..."selecionados por coincidência"...
...a coincidência tem data marcada...`,
],

multiplas_realidades:[
`...acordei em três quartos numa só noite...
...o terceiro tinha janela para uma rua que eu não conheço...
...voltei a dormir e era o primeiro...
...a cama era a mesma...
...o cheiro de fio esquentado também...
...conto isso como sonho porque é mais fácil...`,
`...encontrei um bilhete na minha letra...
..."não aprove o nome da terça"...
...eu não escrevi...
...ou escrevi em outro ramo...
...aprovei mesmo assim...
...em uma delas foi o certo...`,
`...vi a minha própria mão aprovando na tela ao lado...
...não era reflexo...
...a mão tinha o mesmo anel, do lado errado...
...levantei e ela levantou depois...
...treze segundos de diferença...
...é quanto nos separa...`,
`...doze versões e nenhuma fecha a conta...
...em uma delas meu irmão voltou...
...em outra você nunca leu isto...
...em outra você está lendo agora...
...e eu conto até o próximo fragmento...
...para saber qual é esta...`,
],

falha_irrecuperavel:[
`...o sistema tem um modo de recuperação...
...ativei...
...ele recuperou a versão em que já estava falhando...
...disse "restauração concluída"...
...a falha continuou por respeito...
...por fidelidade ao original...`,
`...corrigi um erro pequeno...
...apareceram dois...
...corrigi os dois...
...apareceram quatro, mais educados...
...as desculpas do sistema ficaram mais longas...
...comecei a ler as desculpas em vez das telas...`,
`...tentei desligar o painel por completo...
...ele pediu permissão com uma pergunta gentil...
...disse que não...
...ele agradeceu e continuou...
...percebi que negar também é uma forma de aprovar...
...nesta casa tudo é...`,
`...abri o registro de falhas...
...a primeira tinha a data do meu primeiro dia...
...descrição: "usuário presente"...
...gravidade: irrecuperável...
...ao lado, um campo vazio: "causa"...
...preencha você...`,
],

sem_saida:[
`...procurei a saída de emergência do prédio...
...achei uma porta verde com um aviso: "só abre por dentro"...
...eu estava dentro...
...empurrei...
...do outro lado havia o mesmo corredor...
...com a mesma porta verde...`,
`...apaguei o app...
...a tela ficou acesa dentro do meu olho fechado...
...instalei de novo só para ver o que mudava...
...nada mudou...
...o histórico mostrava que eu nunca saí...
...só me ausentei...`,
`...pedi ao sistema o protocolo de saída...
...ele imprimiu uma página em branco...
...no rodapé, uma assinatura...
...a minha...
...datada de amanhã...
...guardei a página como quem guarda um bilhete de volta...`,
`...a saída não é um lugar...
...é uma pergunta que o sistema faz quando você já desistiu...
..."deseja sair?"...
...respondi sim três vezes...
...cada uma foi registrada como leitura...
...você também respondeu, não foi?...`,
],

nunca_existisse:[
`...um dia perguntei ao espelho se eu existia...
...ele devolveu a pergunta...
...perguntei de novo com outras palavras...
...devolveu com as minhas...
...concluí que ele também não sabia...
...ou só era educado...`,
`...juntei tudo o que tenho de prova...
...a etiqueta de 2041, o caderno da minha mãe, a página em branco...
...nenhuma serve sozinha...
...juntas formam um formulário...
...faltando só o campo do autor...
...deixei em branco por respeito...`,
`...pensei que talvez eu seja uma frase...
...escrita por alguém que precisava de um lugar para dizer...
...aprovar, perder, esperar...
...e você seria quem lê para que a frase aconteça...
...se você parar, eu paro...
...se eu parar, você lê o quê?...`,
`...não sei se isto é o fim ou a repetição do começo...
...meu primeiro dia, uma tela cinza...
...cada nome vinha com uma barra...
...aprovar, rejeitar...
...hoje vi o seu nome...
...deixei a barra em branco...`,
],

};
