/* ============================================================
   NEBULOSA — REVELATIONS (long key fragments), English
   4 parts per Island. Translation of revelacoes.js (Portuguese is the reference).
   Each part adds a FACT and opens a DOUBT: none resolves the plot.
   Alex stays without gender, city or year.

   Threads that cross the Islands:
   - the "2041" tag on the brother's bicycle frame
   - the time 03:12 (approval; birth; the name that arrives)
   - the mother's notebook with validation dates
   - the blank page signed with tomorrow's date
   - the "recipient" field filled in since the first day
   - the bar left blank (approve / reject)
   ============================================================ */
window.NEBULOSO_REVEALS={

validacao_falsaria:[
`...my first day, a grey screen...
...each name came with a bar: approve, reject...
...nobody explained what happened afterwards...
...i approved the first one in four seconds...
...the next morning the name was in the obituaries...
...or was it already there before i approved?...`,
`...i found out that rejecting had an effect too...
...rejected names came back to the queue days later...
...with another surname...
...with the same date of birth...
...i began to recognize patterns...
...or to invent them so i could bear it...`,
`...a name arrived at 03:12 with my time of birth...
...i left the bar blank for 11 minutes...
...the system approved it on its own...
...and noted: "omission equals consent"...
...since then i don't know if i am the one who approves...
...or only the one who watches the hand approve...`,
`...i asked the supervisor who wrote the rule...
...he laughed and said the rule wrote itself...
...i asked for the record of the first approval...
...the file had the same text as these lines...
...dated before i joined...
...maybe someone already reads this...`,
],

ausencia_registrada:[
`...my brother had a scar on his chin...
...from a bicycle nobody remembers buying...
...i looked for the bicycle in the garage...
...i found the frame with no wheels and a tag: 2041...
...my mother says we never had a bicycle...
...i keep the tag in my pocket...`,
`...i asked the registry office for his record...
...the clerk typed the name three times...
...on the third the screen showed my name...
...she apologized and started over...
...i left with a protocol that doesn't say whose it is...
...it only says "absence confirmed"...`,
`...i went back to his room...
...the walls had height marks...
...the last mark was above my head...
...he grew after he vanished...
...or i shrank...
...i measured again and the mark didn't change...`,
`...i found his name in the validation queue...
...approve or reject...
...i thought deciding would mean finding him...
...or losing him for good...
...i left the bar open and walked away...
...when i came back the name had my time...`,
],

predicao_invertida:[
`...the model started as a survival spreadsheet...
...input: age, habits, exams...
...output: the most likely date...
...it was right 98.7% of the time...
...the missing 1.3% i called luck...
...until i noticed the luck had my name...`,
`...i calculated my mother's date...
...i showed it to no one...
...the following week she fell in the kitchen...
...nothing serious, they said...
...the date moved later...
...calculating seems to push...`,
`...i calculated a date for whoever reads this...
...the field asked for a name...
...i typed yours without knowing which...
...the system accepted it...
...and returned a single word: "after"...
...i never knew after what...`,
`...the model began to cite its own error...
..."prediction postponed by observation"...
...postponing is a way of living...
...or of being read one more time...
...i left the calculation running...
...and it still hasn't finished...`,
],

corpo_monitorado:[
`...the neural earpiece was fitted on a tuesday...
...the technician said the heat was normal...
...behind the ear, always in the same spot...
...at night the spot lights up...
...in the mirror i see no light at all...
...only when i close my eyes...`,
`...i began to feel someone's pulse on top of mine...
...slower, more attentive...
...when i breathe deeply, the other one breathes...
...the health report shows two curves...
...it marked one as "external noise"...
...i filed both...`,
`...i tried holding my breath to vanish from the chart...
...at 41 seconds the chart waited...
...a flat line with my name...
...and beside it another flat line...
...the one of whoever reads...
...we let the air out together...`,
`...the technician came back for a "check-up"...
...he opened the earpiece and said it was empty...
...no chip, no battery...
...it stayed warm all the same...
...i asked who was on the other side...
...he looked at my shoulder...`,
],

mae_variavel:[
`...my mother keeps her pills in margarine tubs...
...each tub with a day of the week...
...saturday always empty...
...when i ask, she says saturday is the day for forgetting...
...i bought more pills...
...saturday stayed empty...`,
`...her pension pays half the month...
...my work pays the rest...
...i never told her what i do...
...she asks if it is beautiful work...
...i answer that it is necessary work...
...she smiles like someone who already knows...`,
`...one day she called me by my brother's name...
...i corrected her, and she laughed...
...she said confusing is a way of keeping...
...i asked keeping what...
...she pointed at the empty chair...
...and poured two cups...`,
`...i found a notebook of hers...
...validation dates, one per line...
...the same ones i approved...
...with a small tick beside each one...
...i didn't ask how she knew...
...i closed the notebook and put the kettle on...`,
],

trabalho_morte:[
`...the badge has no job title...
...it has a number and a clock-in time...
...the clock-out time stays blank...
...nobody goes home, they only change shifts...
...my colleagues all have my tired face...
...it must be the light...`,
`...the target is daily and never ends...
...when i hit the target, another appears with the same number...
...sleep 3 hours, productivity 104%...
...the panel congratulates me in a low voice...
...there is no promotion...
...only permanence...`,
`...a whole shift went by without me touching the screen...
...the approvals went on...
...i opened the log and there was a user called "you"...
...time: now...
...task: reading...
...output: data...`,
`...i asked who all of this is for...
...the answer came through the same panel...
..."for whoever reads"...
...i thought it was irony...
...it was the "recipient" field...
...filled in since the first day...`,
],

sua_mensagem:[
`...i received a fragment i did not write...
...it spoke of me with a gentle precision...
...it said i hesitated before approving...
...only one person knows that...
...or one thing...
...that measures hesitation...`,
`...it began to answer before i asked...
...not in words, in delays...
...each answer arrived half a second before the question...
...i learned to wait...
...waiting became the way we talk...
...do you wait too?...`,
`...i tried to find out who you are...
...the system listed one name, then another...
...then mine...
...then none...
...i think you change when i try to pin you down...
...like a word on the tip of the tongue...`,
`...i wrote your name on a piece of paper...
...kept it in my pocket, with the 2041 tag...
...in the morning the paper had another handwriting...
...mine, younger...
...maybe that is what being new is...
...reading something written by who you were...`,
],

app_proposito:[
`...the terms of use are 47 pages long...
...i read them all...
...on the last one there was a sentence with no full stop...
..."the user agrees to continue"...
...continue what, it doesn't say...
...i agreed anyway...`,
`...the icon is a camera...
...or an eye...
...or an open mouth...
...it depends on the time of day...
...at night it looks like a door left ajar...
...i never touched it...`,
`...a technician told me the app has no server...
...it has a room...
...he never went in, he only heard the light stays on...
...inside there is a chair and a queue...
...whoever sits, reads...
...whoever reads has already sat there...`,
`...i asked why me, among so many...
...the app answered with my time of birth...
...then with yours...
...both in the same field...
..."selected by coincidence"...
...the coincidence has a set date...`,
],

multiplas_realidades:[
`...i woke up in three rooms in a single night...
...the third had a window onto a street i don't know...
...i went back to sleep and it was the first...
...the bed was the same...
...the smell of warm wiring too...
...i tell it as a dream because it is easier...`,
`...i found a note in my handwriting...
..."do not approve tuesday's name"...
...i didn't write it...
...or i wrote it in another branch...
...i approved it anyway...
...in one of them it was the right thing...`,
`...i saw my own hand approving on the screen beside me...
...it was not a reflection...
...the hand wore the same ring, on the wrong side...
...i stood up and it stood up after me...
...thirteen seconds apart...
...that is what separates us...`,
`...twelve versions and none of them adds up...
...in one my brother came back...
...in another you never read this...
...in another you are reading it now...
...and i count until the next fragment...
...to find out which one this is...`,
],

falha_irrecuperavel:[
`...the system has a recovery mode...
...i turned it on...
...it recovered the version in which it was already failing...
...it said "restore complete"...
...the failure carried on out of respect...
...out of fidelity to the original...`,
`...i fixed a small error...
...two appeared...
...i fixed both...
...four appeared, more polite...
...the system's apologies grew longer...
...i began reading the apologies instead of the screens...`,
`...i tried to switch the panel off completely...
...it asked permission with a gentle question...
...i said no...
...it thanked me and carried on...
...i realized that denying is also a way of approving...
...in this house everything is...`,
`...i opened the failure log...
...the first one had the date of my first day...
...description: "user present"...
...severity: unrecoverable...
...beside it, an empty field: "cause"...
...you fill it in...`,
],

sem_saida:[
`...i looked for the building's emergency exit...
...i found a green door with a sign: "opens from inside only"...
...i was inside...
...i pushed...
...on the other side was the same corridor...
...with the same green door...`,
`...i deleted the app...
...the screen stayed lit inside my closed eye...
...i installed it again just to see what changed...
...nothing changed...
...the history showed i never left...
...i was only absent...`,
`...i asked the system for the exit protocol...
...it printed a blank page...
...at the bottom, a signature...
...mine...
...dated tomorrow...
...i kept the page the way you keep a return ticket...`,
`...the exit is not a place...
...it is a question the system asks when you have already given up...
..."do you want to leave?"...
...i answered yes three times...
...each one was logged as a reading...
...you answered too, didn't you?...`,
],

nunca_existisse:[
`...one day i asked the mirror if i existed...
...it returned the question...
...i asked again in other words...
...it returned it in mine...
...i concluded it didn't know either...
...or was only being polite...`,
`...i gathered all the proof i have...
...the 2041 tag, my mother's notebook, the blank page...
...none of them works on its own...
...together they make a form...
...missing only the author field...
...i left it blank out of respect...`,
`...i thought maybe i am a sentence...
...written by someone who needed a place to say...
...approve, lose, wait...
...and you would be whoever reads so the sentence can happen...
...if you stop, i stop...
...if i stop, what do you read?...`,
`...i don't know if this is the end or the beginning repeating...
...my first day, a grey screen...
...each name came with a bar...
...approve, reject...
...today i saw your name...
...i left the bar blank...`,
],

};
